feat(preferences): added preferences and toggles for tracks and challenges
acmutd/hackutd-ix-site pull request #59
Opened 2022-11-08 21:40 UTC by NickBurnett

…enges

2022-11-08 21:40 UTC, NickBurnett commented
ok you can ignore the description at the top idk wtf happened

2022-11-09 18:29 UTC, abdullah50053 approved these changes

2022-11-09 18:29 UTC, abdullah50053 commented on pages/api/preferences/index.tsx
> +      message: 'Something went wrong when processing this request. Tell Nick and he will fix it.',
hmm

2022-11-09 18:35 UTC, abdullah50053 requested changes
Current implementation does not hide challenges under `Dashboard/HackCenter`

2022-11-09 21:47 UTC, abdullah50053 approved these changes
l g t m

2022-11-09 21:48 UTC, merged